myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('mogibe_help/', views.mogibe_help, name='mogibe_help'),
    path('mogibe_about/', views.mogibe_about, name='mogibe_about'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
] 

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/orders/models.py
from django.db import models
from shop.models import Product

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return f'Order {self.id}'
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
class OrderItem(models.Model):
    order = models.ForeignKey(Order,
    related_name='items',
    on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
    related_name='order_items',
    on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    def __str__(self):
        return str(self.id)
    def get_cost(self):
        return self.price * self.quantity

myshop/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self) :
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    
    def __str__(self) :
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

myshop/cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                    choices=PRODUCT_QUANTITY_CHOICES,
                                    coerce=int)
    override = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

myshop/orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
        'postal_code', 'city']

myshop/cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data 
        cart.add(product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                        product=item['product'],
                                        price=item['price'],
                                        quantity=item['quantity'])
            # clear the cart
            cart.clear()
            return render(request,
                        'orders/order/created.html',
                        {'order': order})
    else:
        form = OrderCreateForm()
    return render(request,
                'orders/order/create.html',
                {'cart': cart, 'form': form})

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm 

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category' : category, 'categories' : categories, 'products' : products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product' : product, 'cart_product_form': cart_product_form})

def mogibe_help(requset):
    context={}
    return render(requset, 'shop/product/help.html', context)

def mogibe_about(requset):
    context={}
    return render(requset, 'shop/product/about.html', context)

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
   Your shopping cart
{% endblock %}
{% block content %}
    {% with total_items=cart|length %}
        {% if total_items > 0 %}
            <div class="cart-body-content">
                <h1>Your shopping cart</h1>
                <table class="cart2">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Name</th>
                            <th>Quantity</th>
                            <th>Remove</th>
                            <th>Unit price</th>
                            <th>Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                            {% with product=item.product %}
                                <tr>
                                    <td>
                                        <a href="{{ product.get_absolute_url }}">
                                            <img src="{% if product.image %}{{ product.image.url}}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                                        </a>
                                    </td>
                                    <td class="nm">{{ product.name }}</td>
                                    <td>
                                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                        {{ item.update_quantity_form.quantity }}
                                        {{ item.update_quantity_form.override }}
                                        <input type="submit" value="Update">
                                        {% csrf_token %}
                                        </form>
                                        </td>
                                    <td>
                                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                            <input type="submit" value="Remove">
                                            {% csrf_token %}
                                        </form>
                                    </td>
                                    <td class="num">Ksh.{{ item.price }}</td>
                                    <td class="num">Ksh.{{ item.total_price }}</td>
                                </tr>
                            {% endwith %}
                        {% endfor %}
                        <tr class="total">
                            <td>Total Amount</td>
                            <td colspan="4"></td>
                            <td class="num">Ksh.{{ cart.get_total_price }}</td>
                        </tr>
                    </tbody>
                </table>
                <p class="text-right">
                    <a href="{% url 'shop:product_list' %}" class="buttonlight">Go to products</a>
                    <a href="{% url 'orders:order_create' %}" class="button">Make Purchase</a>
                </p>
            </div>
        {% else %}
            <div class="Your-Cart-Is">
                <div class="your-cart-de">
                    <h1>Your Cart is Empty</h1>
                    <p>Please add a product to your cart and make purchases on mogibe. Just click the Go to Product bellow to add a product to your cart </p>
                </div>
                <a href="{% url 'shop:product_list' %}" class="buttonlight">Go to Products</a>
            </div>
        {% endif %}
    {% endwith %}
{% endblock %}

myshop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}
    Giock.com|Checkout
{% endblock %}
{% block content %}
    <div class="oder">
        <h1>Checkout</h1>
        <div class="order-details">
            <div class="order-info">
                <h3>Your order</h3>
                <ul>
                    {% for item in cart %}
                        <li>
                            {{ item.quantity }}x {{ item.product.name }}
                            <span>${{ item.total_price }}</span>
                        </li>
                    {% endfor %}
                </ul>
                <p>Total: ${{ cart.get_total_price }}</p>
            </div>
            <a href="{% url 'shop:product_list' %}" class="buttonlight">Go to Products</a>
            <form method="post" class="order-form">
                {{ form.as_p }}
                <p><input type="submit" value="Place order"></p>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

myshop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %}
    Special Thanks from Giock.com
{% endblock %}
{% block content %}
    <div class="order-created-content">
        <h1>Thank you for shoping with us</h1>
        <p>Your order has been successfully completed. <br>Your order number is: <br> <span>rmkdva0000{{ order.id }}0000MgBt.0.tech{{ order.id }}</span></p>
    </div>
{% endblock %}

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
       <meta charset="UTF-8">
       <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>{% block title %}Giock.com{% endblock %}</title>
       <link href="{% static 'css/base.css' %}" rel="stylesheet">
       <script src="https://kit.fontawesome.com/a8ba985590.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="nav-bar">
            <div id="header">
                <a href="/" class="logo">
                    <img src="{% static 'img/open-shop.jpg' %}">
                </a>
            </div>
            <h1><span class="mo">Gi</span><span class="gi">oc</span><span class="be">k</span><span class="tech">.Tech</span></h1>
            <div id="subheader">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="{% url 'shop:mogibe_help' %}">Help</a></li>
                    <li><a href="{% url 'shop:mogibe_about' %}">About</a></li>
                </ul>
                <i class="fas fa-cart-plus"></i>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                            <a href="{% url 'cart:cart_detail' %}"></a>
                                {{ total_items }}
                            </a>
                        {% else %}
                            0
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <footer>
            <div class="footer-content">
                <div class="quick-links">
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li><a href="{% url 'shop:mogibe_help' %}">Help</a></li>
                        <li><a href="{% url 'shop:mogibe_about' %}">About</a></li>
                        <li><a href="{% url 'cart:cart_detail' %}">cart</a></li>
                    </ul>
                </div>
                <div class="social-media">
                    <h1>follow us on</h1>
                    <ul>
                        <li><a href="https://www.facebook.com">Facebook</a></li>
                        <li><a href="https://twitter.com">Twitter</a></li>
                        <li><a href="https://www.instagram.com">Instergram</a></li>
                        <li><a href="https://www.linkedin.com">linked In</a></li>
                    </ul>
                </div>
                <div class="contacts">
                    <h1>Contact us</h1>
                    <ul>
                        <li>GideonKiruiEmbu</li>
                        <li>0712345678</li>
                        <li>Embu, University of Embu</li>
                        <li>giock@gmail.com</li>
                    </ul>
                </div>
                <div class="feedback">
                    <form action="href='/'" method="post">
                        <input class="email" type="email" placeholder="email" required>
                        <textarea name="" id="" cols="30" rows="10" placeholder="Leave a comment here"></textarea>
                        <input class="btn" type="button" value="submit">
                    </form>
                </div>
            </div>
            <h5>copyright&copy;2021-Giock.com</h5>
        </footer>
    </body>
</html>

myshop/shop/templates/shop/product/about.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    About Giock.com
{% endblock %}
{% block content %}
    <div class="small-container">
        <div class="body-contents">
            <div class="mogibe-logo">
                <img src="{% static 'img/open-shop.jpg' %}">
            </div>
            <div class="description">
                <h1>Hello, Here is What You May need to Know about Giock.com!!!!</h1>
            </div>
        </div>
        <div class="mgbhstry">
            <p>Giock.com is a project by Gideon Kirui a students at the univeristy of embu, the project is a class assignment to be submited to his lectuer(Dkt Michael Ndege) a lecturer in the same University. <br> profile for the designer(Gideon Kirui Ochieng) is shown bellow</p>
        </div>
        <div class="designers">
            <h1 id="triop">The Designers</h1>
            <div class="row">
               <div class="col-3">
                 <img src="{% static 'img/my_photo1.jpg' %}">
                 <h3>Gideon Kirui</h3>
                 <hr>
                 <div class="desingner-profile">
                      <p>University of Embu</p>
                      <p>Bsc. InfoTech</p>
                      <p>6-600 Embu Kenya</p>
                      <div class="social-media">
                          <p>Twitter:@thegideon's</p>
                          <p>Facebook: gideon</p>
                          <p>Instagram: gideonkirui_b</p>
                          <p>call: 0712345678</p>
                   </div>
                 </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
    <div class="product-detail-body">
        <div class="product-detail">
            <h2>
                <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
            </h2>
            <div class="product-desc">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/img-1.jfif' %}{% endif %}">
                <div class="details-description">
                    <h1>{{ product.name }}</h1>
                    <p class="price">${{ product.price }}</p>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <input type="submit" value="Add to cart">
                    </form>
                    {{ product.description|linebreaks }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myshop/shop/templates/shop/product/help.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Giock.com Help Desk
{% endblock %}
{% block content %}
    <div class="body-Contents">
        <div class="col-2">
            <div class="the-container">
                <h1>Hi! are you wondering about Giock.com?, maybe you can look at some of the foolowing asnswered questions</h1>
                <details>
                    <summary>More about Giock.com</summary>
                    <div class="msg">
                        <p>Giock.com is just a simple web project that has been developed by Gideon Kirui from embu
                            university as an assignment that should be subjected for marking by His Lectuerer
                            the project is an Ecomerce-like site that can be deemed as an online or a mobile shop
                        </p>
                    </div>
                </details>
                <details>
                    <summary>How To Get Started with Giock.com</summary>
                    <p>Getting started is as simple as you just deed. just accesing the link is a good start and you are good to go</p>
                </details>
                <details>
                    <summary> What is needed to get started with Giock.com</summary>
                    <p>Oh! No, you need not to worry so much about this, the is no  big deal with Giock.com, no skills required, just your smartphone and the urge to access a website is enough</p>
                </details>
                <details>
                   <summary>How Does Giock.com operate?</summary>
                   <p>Giock.com is mearly a simple website with a disirable user interface where a visitor to the site can navigate the functionality</p>
                </details>
                <details>
                   <summary>Can I Trust Giock.com?</summary>
                   <p>Actualy there is no need for even having a thought of trusting Giock.com, it has nothing to do with your personal data just navigate the site and thats all, kindly ndo submit your personal data even when asked to ( you may use a invalid data) maybe for test </p>
                </details>
                <details>
                   <summary>Can Someone sell products on Giock.com site?</summary>
                   <p>No! Giock.com is not a genuine site to do any business as at now but if you have an idea on how I can advance the site the fill free to reach me by commenting on the comment area in the footer( I mean the lower part of the site)</p>
                </details>
                <details>
                   <summary>How Can I reach Giock.com customer care?</summary>
                   <p>Oh! sorry there is no service that the site offers as at now but if you fill like there is a gap that Giok.com can fill then kindly don't essitate to reach me</p>
                </details>
                <details>
                   <summary>Where is Giock.located Located?</summary>
                   <p>Giock is a site developed by university of embu student thus its headquaters can be traced to university of embu</p>
                </details>
                <p><a href="#">see more...</a></p>
            </div>
        </div>
    </div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Giock.com{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'shop:product_list' %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"
                {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products
        {% endif %}</h1>
        <div class="all-products-list">
            {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/logo.jpg' %}{% endif %}"/>
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                <br>
                Ksh.{{ product.price }}
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}